version: '3.8'
services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_DB=temba
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - "5432:5432"
    # networks:
    #   - network1
  

  redis:
    image: "redis:latest"
    volumes:
      - ./redis-data:/data
    ports: 
      - "6379:6379"
    # networks:
    #   - network1

# networks:
#   network1:
#     name: my-network
#     external: true